FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .

ARG PORT
ENV PORT=${PORT}

ARG REACT_APP_BASE_API_URL
ENV REACT_APP_BASE_API_URL=${REACT_APP_BASE_API_URL}

ARG REACT_APP_PUSHER_KEY
ENV REACT_APP_PUSHER_KEY=${REACT_APP_PUSHER_KEY}

ARG REACT_APP_PN_NEW_REVIEW_CHANNEL
ENV REACT_APP_PN_NEW_REVIEW_CHANNEL=${REACT_APP_PN_NEW_REVIEW_CHANNEL}

ARG REACT_APP_DEFAULT_PRODUCT_SLUG
ENV REACT_APP_DEFAULT_PRODUCT_SLUG=${REACT_APP_DEFAULT_PRODUCT_SLUG}

RUN yarn build

# production stage
FROM socialengine/nginx-spa:latest as production-stage
COPY --from=build-stage /app/build /app
RUN chmod -R 777 /app
EXPOSE ${PORT}
